version: '3.5'

services:
  apiinpulseadm:
    image: ${DOCKER_REGISTRY-}apiinpulseadm
    container_name: apiinpulseadm    
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=192.168.224.1
      - PASSWORD=root